### ISSUE TITLE
알람기능

### ISSUE THREAD

**Issue by sumi-0011** [pgrm-study-website/Frontend#16]
알람 기능을
- 링크를 이동해 알람 페이지로 넘어가는 방식
- 알람 아이콘을 클릭하면 옆에 알람 리스트 모달창이 나타나는 방식

어느 방식으로 하면 될까요?

**Comment by seuha516** [comment]
아이콘 클릭하면 옆에 최근 알림 3개정도 뜨는 모달창이 나오게 하고, 더보기 버튼을 누르면 알람 페이지로 넘어가는 건 어떨까요?
