### ISSUE TITLE
validateDOMNesting bug

### ISSUE THREAD

**Issue by sumi-0011** [pgrm-study-website/Frontend#27]
![image](https://user-images.githubusercontent.com/49177223/161516267-8d51e7fb-9074-47c4-8de6-83c4f39d188e.png)
언제부턴가 이러한 에러가 뜨는데 혹시 어디서 발생한건지 아시나요?

**Comment by seuha516** [comment]
![image](https://user-images.githubusercontent.com/79067549/161517990-a7606939-9b53-4634-80a2-c34e3e37c6ad.png)

> li cannot appear as a descendant of li.

> li 안에 li를 넣을 수 없습니다.

해결법: const More = styled.div 등으로 바꿔주세요
