### ISSUE TITLE
로그인/회원가입 피드백

### ISSUE THREAD

**Issue by seuha516** [pgrm-study-website/Frontend#5]
- (사다리꼴에 있는 텍스트) '플밍', 'login' 폰트를 바꾸면 좋겠어요
- (사다리꼴에 있는 텍스트) login을 로그인으로 바꾸거나, 회원가입을 signup으로 바꿔서 통일하는게 좋아보입니다
- 로그인, 회원가입 버튼에 &:hover{ cursor:pointer }
- 구글, 깃허브 버튼도 hover 추가
- `<a href="..."/>` 을 `<Link to="..."/>` 로 바꿔야 할 것 같습니다 (`import { Link } from 'react-router-dom';`)
- 로그인 페이지에서 회원가입을 누르면 /signup이 아니라 /join으로 가는데, 어느 한쪽을 바꿔서 통일해줘야 합니다
- 회원가입 페이지에서 인풋창이 사다리꼴이랑 겹칩니다
- 회원가입 창에서 Id/Pw 자동완성이 됩니다. 안 되게 해야겠습니다
- 회원가입 버튼을 누르면 각각의 인풋을 정규표현식으로 검사해서 만약 올바르지 않은 이메일 형식이면 alert를 띄우면 어떨까요?
- 회원가입쪽에 password랑 confirm 오타 있습니다
- 로그인/회원가입 창에서도 다시 홈 화면으로 돌아갈 버튼이 있으면 좋겠는데 어디 둘지는 생각해봐야겠네요
- pwd_find 창도 비슷한 디자인으로 구현하면 될 것 같습니다

```
var usernamePattern = /[^a-zA-Z0-9]/g;
var passwordPattern = /[ㄱ-ㅎㅏ-ㅣ가-힣]/g;
var emailRegex = /^[0-9a-zA-Z]([-_\.]?[0-9a-zA-Z])*@[0-9a-zA-Z]([-_\.]?[0-9a-zA-Z])*\.[a-zA-Z]{2,3}$/;
```
제가 예전에 개발할때 썼던 정규표현식들입니다

**Comment by seuha516** [comment]
- Login.tsx에서 LinkItem 변수가 선언되었지만 사용되지 않습니다
- `<div className="social__title"></div>` 도 사용되지 않습니다 (나중에 쓰실 계획이시라면 무시해 주세요)
- Login, Signup 두 페이지 모두 창 width를 줄이면 글자가 빠져나옵니다
- `<Label>` 안에 있는 텍스트 첫 글자를 소문자나 대문자 중 하나로 통일하면 좋겠습니다!

**Comment by sumi-0011** [comment]
1. LinkItem 수정할게요
2. 넣을지 말지 고민되서 일단 보류했습니다!
3. 한번에 수정할게용!
4. 대문자가 이쁜거 같은데 이건 한번 더보고 통일할게용!
